name: Flutter

on:
  push:
    branches:
    paths-ignore:
      - "**.md"
  pull_request:
    branches-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: flutter analyze
      - run: flutter test test/

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - run: flutter build apk

      - uses: actions/upload-artifact@v4
        with:
          name: Apk
          path: |
            build/app/outputs/flutter-apk/app-release.apk
