name: Flutter

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      - name: Rename
        run: |
          rename app ciyue build/app/outputs/flutter-apk/*
          rename app ciyue build/app/outputs/bundle/release/*

      - uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/ciyue-*-release.apk
            build/app/outputs/bundle/release/ciyue-release.aab

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/ciyue-*-release.apk,build/app/outputs/bundle/release/ciyue-release.aab"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
