name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.0
          cache: true

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks

      - name: Create key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      - name: Rename .apk
        run: |
          cd build/app/outputs/flutter-apk
          mv app-release.apk ciyue-universal-release.apk
          mv app-armeabi-v7a-release.apk ciyue-armeabi-v7a-release.apk
          mv app-arm64-v8a-release.apk ciyue-arm64-v8a-release.apk
          mv app-x86_64-release.apk ciyue-x86_64-release.apk

      - name: Rename .aab
        run: |
          cd build/app/outputs/bundle/release
          mv app-release.aab ciyue-release.aab

      - uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/ciyue-*-release.apk
            build/app/outputs/bundle/release/ciyue-release.aab

  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate a changelog for release
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Generate a CHANGELOG.md
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/ciyue-*-release.apk,build/app/outputs/bundle/release/ciyue-release.aab"
          tag: ${{ github.ref_name }}
          body: ${{ needs.changelog.outputs.release_body }}
